import React, { useState, useEffect, useCallback } from 'react';
import { Settings, Save, RefreshCw, Sliders, CheckCircle2, AlertCircle, FileText, HardDrive, Cpu, Download } from 'lucide-react';
import { desktop } from '../lib/desktop';

export const SettingsTab: React.FC = () => {
  const [profile, setProfile] = useState<'lite' | 'standard' | 'pro' | 'airgapped' | 'enterprise'>('standard');
  const [configContent, setConfigContent] = useState('');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [statusMsg, setStatusMsg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const loadConfig = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      if (desktop.isDesktop) {
        const file = await desktop.configLoad();
        setConfigContent(typeof file === 'string' ? file : (file as any).content || '');
      } else {
        setConfigContent(`# Oxide-Tech Local Agent OS Configuration
# Generated by oxide-agent-studio

[profile]
name = "standard"

[gateway]
host = "127.0.0.1"
port = 8080
latency_threshold_ms = 2000
quality_threshold = 0.85
max_retries = 5

[thinker]
provider = "ollama"
model = "deepseek-coder-v2"
temperature = 0.7
max_tokens = 4096

[oxide_embed]
budget = 1500
stair_enabled = true

[verifier]
enabled = true
phases = 7
`);
      }
    } catch (err: any) {
      setError(err?.message || String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  const handleSave = useCallback(async () => {
    setSaving(true);
    setError(null);
    setStatusMsg(null);
    try {
      if (desktop.isDesktop) {
        await desktop.configSave(configContent);
        setStatusMsg('Configuration successfully validated and saved to disk.');
      } else {
        setStatusMsg('Configuration updated (in-memory web mode).');
      }
      setTimeout(() => setStatusMsg(null), 3000);
    } catch (err: any) {
      setError(err?.message || String(err));
    } finally {
      setSaving(false);
    }
  }, [configContent]);

  const generateConfig = useCallback((profileType: string) => {
    const configs: Record<string, string> = {
      lite: `[profile]
name = "lite"

[gateway]
host = "127.0.0.1"
port = 8080
latency_threshold_ms = 3000
max_retries = 3

[thinker]
provider = "ollama"
model = "deepseek-coder-v2"
temperature = 0.7

[oxide_embed]
budget = 500
stair_enabled = true`,
      standard: `[profile]
name = "standard"

[gateway]
host = "127.0.0.1"
port = 8080
latency_threshold_ms = 2000
quality_threshold = 0.85
max_retries = 5

[thinker]
provider = "ollama"
model = "deepseek-coder-v2"
temperature = 0.7
max_tokens = 4096

[oxide_embed]
budget = 1500
stair_enabled = true

[verifier]
enabled = true
phases = 7`,
      pro: `[profile]
name = "pro"

[gateway]
host = "127.0.0.1"
port = 8080
latency_threshold_ms = 1000
quality_threshold = 0.95
max_retries = 10

[thinker]
provider = "ollama"
model = "deepseek-coder-v2"
temperature = 0.3
max_tokens = 8192

[oxide_embed]
budget = 3000
stair_enabled = true

[verifier]
enabled = true
phases = 7

[hardware]
gpu_acceleration = true
nvidia_compute = true`,
    };
    return configs[profileType] || configs.standard;
  }, []);

  const handleProfileChange = useCallback((newProfile: string) => {
    const p = newProfile as typeof profile;
    setProfile(p);
    setConfigContent(generateConfig(newProfile));
  }, [generateConfig]);

  useEffect(() => {
    loadConfig();
  }, []);

  return (
    <div className="space-y-6 font-sans">
      {/* Header */}
      <div className="bg-[#111217] border border-[#232530] rounded-2xl p-6 shadow-xl relative overflow-hidden bg-[radial-gradient(ellipse_at_top_right,rgba(245,158,11,0.04)_0%,transparent_70%)]">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[#232530]">
          <div>
            <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <Settings className="w-4 h-4 text-amber-400" />
              Configuration
            </h2>
            <p className="text-[11px] mono text-gray-400 mt-1">
              Profile: <span className="text-amber-400">{profile}</span> · config.toml
            </p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={loadConfig}
              disabled={loading}
              className="px-2.5 py-1 rounded bg-[#18181e] hover:bg-[#202330] border border-[#2c2f3d] text-[10px] mono text-gray-300 flex items-center gap-1.5 transition cursor-pointer"
            >
              <RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />
              Reload
            </button>
            <button
              onClick={handleSave}
              disabled={saving || loading}
              className="px-4 py-2 rounded-lg bg-gradient-to-r from-amber-600 to-amber-500 hover:from-amber-500 hover:to-amber-400 text-zinc-950 text-xs font-bold uppercase tracking-wider transition-all flex items-center gap-2 cursor-pointer disabled:opacity-50 shadow-[0_0_12px_rgba(245,158,11,0.2)]"
            >
              <Save className="w-3 h-3" />
              {saving ? 'Saving...' : 'Save Config'}
            </button>
          </div>
        </div>

        {/* Profile Switcher */}
        <div className="pt-4">
          <div className="text-[10px] font-mono uppercase text-zinc-500 tracking-wider mb-2">Profile</div>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2.5">
            {(['lite', 'standard', 'pro', 'airgapped', 'enterprise'] as const).map((p) => (
              <button
                key={p}
                onClick={() => handleProfileChange(p)}
                className={`px-3 py-2 rounded-lg text-[11px] font-mono font-medium transition cursor-pointer border ${
                  profile === p
                    ? 'bg-amber-500/10 border-amber-500/30 text-amber-400'
                    : 'bg-[#161822] border-[#242738] text-gray-400 hover:text-gray-200'
                }`}
              >
                {p.charAt(0).toUpperCase() + p.slice(1)}
              </button>
            ))}
          </div>
          <div className="text-[10px] mono text-gray-500 mt-0.5">{profile} profile</div>
        </div>

        {/* Status Messages */}
        {statusMsg && (
          <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs mono flex items-center gap-2 mt-4">
            <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
            {statusMsg}
          </div>
        )}
        {error && (
          <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs mono flex items-center gap-2 mt-4">
            <AlertCircle className="w-3.5 h-3.5 shrink-0" />
            {error}
          </div>
        )}
      </div>

      {/* Local GGUF & Model Setup Card */}
      <div className="bg-[#111217] border border-[#232530] rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-[#232530]">
          <div>
            <h3 className="text-xs font-bold text-white flex items-center gap-2">
              <HardDrive className="w-3.5 h-3.5 text-amber-400" />
              Local Model & GGUF Storage
            </h3>
            <p className="text-[11px] mono text-gray-400 mt-0.5">
              Place .gguf weights in <code className="text-amber-400">~/models/</code> or <code className="text-amber-400">/var/lib/oxide-tech/models/</code>
            </p>
          </div>
          <span className="text-[9px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-semibold">
            OFFLINE READY
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
          <div className="p-3.5 rounded-xl bg-[#0c0d12] border border-[#232530] space-y-2">
            <div className="font-bold text-white flex items-center gap-1.5">
              <Cpu className="w-3.5 h-3.5 text-amber-400" />
              Option 1: Ollama Model Runner
            </div>
            <p className="text-[11px] text-zinc-400">
              Run any GGUF or standard model locally with zero setup:
            </p>
            <div className="p-2 rounded bg-[#161822] border border-[#242738] font-mono text-[10px] text-amber-300 select-all">
              ollama pull qwen2.5-coder:7b-instruct-q4_K_M
            </div>
          </div>

          <div className="p-3.5 rounded-xl bg-[#0c0d12] border border-[#232530] space-y-2">
            <div className="font-bold text-white flex items-center gap-1.5">
              <Download className="w-3.5 h-3.5 text-amber-400" />
              Option 2: Direct GGUF File Download
            </div>
            <p className="text-[11px] text-zinc-400">
              Download any .gguf file directly to your models folder:
            </p>
            <div className="p-2 rounded bg-[#161822] border border-[#242738] font-mono text-[10px] text-amber-300 select-all">
              mkdir -p ~/models && curl -L -o ~/models/model.gguf &lt;URL&gt;
            </div>
          </div>
        </div>
      </div>

      {/* Config Editor */}
      <div className="bg-[#111217] border border-[#232530] rounded-2xl p-6 shadow-xl space-y-3">
        <div className="flex items-center justify-between pb-3 border-b border-[#232530]">
          <h3 className="text-xs font-bold text-white flex items-center gap-2">
            <FileText className="w-3.5 h-3.5 text-amber-400" />
            config.toml
          </h3>
          <span className="text-[10px] font-mono text-zinc-500">{profile} profile</span>
        </div>
        <textarea
          value={configContent}
          onChange={(e) => setConfigContent(e.target.value)}
          className="w-full bg-[#0c0d12] border border-[#232530] rounded-xl p-4 text-[11px] mono text-orange-100/90 leading-relaxed font-mono min-h-[420px] focus:outline-none focus:border-amber-500/60 resize-y"
          spellCheck={false}
        />
      </div>
    </div>
  );
};
