import React, { useState, useEffect, useCallback } from 'react';
import {
  Settings,
  Save,
  RefreshCw,
  Sliders,
  CheckCircle2,
  AlertCircle,
  FileText,
  HardDrive,
  Cpu,
  Download,
  ShieldCheck,
  Zap,
  Globe,
  Share2,
  Copy,
  Sparkles,
  Wifi,
} from 'lucide-react';
import { desktop, startCloudflareTunnel, stopCloudflareTunnel, getTunnelStatus, startLanBroadcast, stopLanBroadcast } from '../lib/desktop';
import { UpdateModal } from './UpdateModal';
import { UnslothMigrateModal } from './UnslothMigrateModal';
import { TunnelStatusDto, LanBroadcastStatusDto } from '../types';

export const SettingsTab: React.FC = () => {
  const [isUpdateModalOpen, setIsUpdateModalOpen] = useState(false);
  const [isMigrateModalOpen, setIsMigrateModalOpen] = useState(false);
  const [profile, setProfile] = useState<'lite' | 'standard' | 'pro' | 'airgapped' | 'enterprise'>('standard');
  const [configContent, setConfigContent] = useState('');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [statusMsg, setStatusMsg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Tunnel state
  const [tunnelStatus, setTunnelStatus] = useState<TunnelStatusDto>({
    is_active: false,
    public_url: null,
    local_port: 8080,
    client_count: 0,
  });
  const [tunnelPort, setTunnelPort] = useState(8080);
  const [isTogglingTunnel, setIsTogglingTunnel] = useState(false);
  const [copiedUrl, setCopiedUrl] = useState(false);

  // LAN state
  const [lanStatus, setLanStatus] = useState<LanBroadcastStatusDto>({
    is_broadcasting: false,
    service_name: 'Oxide-Tech-Local-Agent',
    ip_addresses: [],
    port: 8080,
  });
  const [isTogglingLan, setIsTogglingLan] = useState(false);

  useEffect(() => {
    getTunnelStatus().then(setTunnelStatus).catch(() => {});
  }, []);

  const handleToggleTunnel = async () => {
    setIsTogglingTunnel(true);
    try {
      if (tunnelStatus.is_active) {
        await stopCloudflareTunnel();
        setTunnelStatus({ is_active: false, public_url: null, local_port: tunnelPort, client_count: 0 });
      } else {
        const res = await startCloudflareTunnel(tunnelPort);
        setTunnelStatus(res);
      }
    } catch (err: any) {
      setError(err?.message || String(err));
    } finally {
      setIsTogglingTunnel(false);
    }
  };

  const handleToggleLan = async () => {
    setIsTogglingLan(true);
    try {
      if (lanStatus.is_broadcasting) {
        await stopLanBroadcast();
        setLanStatus((prev) => ({ ...prev, is_broadcasting: false }));
      } else {
        const res = await startLanBroadcast(tunnelPort);
        setLanStatus(res);
      }
    } catch (err: any) {
      setError(err?.message || String(err));
    } finally {
      setIsTogglingLan(false);
    }
  };

  const copyPublicUrl = () => {
    if (tunnelStatus.public_url) {
      navigator.clipboard.writeText(tunnelStatus.public_url);
      setCopiedUrl(true);
      setTimeout(() => setCopiedUrl(false), 2000);
    }
  };

  const loadConfig = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      if (desktop.isDesktop) {
        const file = await desktop.configLoad();
        setConfigContent(typeof file === 'string' ? file : (file as any).content || '');
      } else {
        setConfigContent(`# Oxide-Tech Local Agent OS Configuration
# Generated by oxide-agent-studio

[profile]
name = "standard"

[gateway]
host = "127.0.0.1"
port = 8080
latency_threshold_ms = 2000
quality_threshold = 0.85
max_retries = 5

[thinker]
provider = "ollama"
model = "deepseek-coder-v2"
temperature = 0.7
max_tokens = 4096

[oxide_embed]
budget = 1500
stair_enabled = true

[verifier]
enabled = true
phases = 7
`);
      }
    } catch (err: any) {
      setError(err?.message || String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  const handleSave = useCallback(async () => {
    setSaving(true);
    setError(null);
    setStatusMsg(null);
    try {
      if (desktop.isDesktop) {
        await desktop.configSave(configContent);
        setStatusMsg('Configuration successfully validated and saved to disk.');
      } else {
        setStatusMsg('Configuration updated (in-memory web mode).');
      }
      setTimeout(() => setStatusMsg(null), 3000);
    } catch (err: any) {
      setError(err?.message || String(err));
    } finally {
      setSaving(false);
    }
  }, [configContent]);

  const generateConfig = useCallback((profileType: string) => {
    const configs: Record<string, string> = {
      lite: `[profile]
name = "lite"

[gateway]
host = "127.0.0.1"
port = 8080
latency_threshold_ms = 3000
max_retries = 3

[thinker]
provider = "ollama"
model = "deepseek-coder-v2"
temperature = 0.7

[oxide_embed]
budget = 500
stair_enabled = true`,
      standard: `[profile]
name = "standard"

[gateway]
host = "127.0.0.1"
port = 8080
latency_threshold_ms = 2000
quality_threshold = 0.85
max_retries = 5

[thinker]
provider = "ollama"
model = "deepseek-coder-v2"
temperature = 0.7
max_tokens = 4096

[oxide_embed]
budget = 1500
stair_enabled = true

[verifier]
enabled = true
phases = 7`,
      pro: `[profile]
name = "pro"

[gateway]
host = "127.0.0.1"
port = 8080
latency_threshold_ms = 1000
quality_threshold = 0.95
max_retries = 10

[thinker]
provider = "ollama"
model = "deepseek-coder-v2"
temperature = 0.3
max_tokens = 8192

[oxide_embed]
budget = 3000
stair_enabled = true

[verifier]
enabled = true
phases = 7

[hardware]
gpu_acceleration = true
nvidia_compute = true`,
    };
    return configs[profileType] || configs.standard;
  }, []);

  const handleProfileChange = useCallback((newProfile: string) => {
    const p = newProfile as typeof profile;
    setProfile(p);
    setConfigContent(generateConfig(newProfile));
  }, [generateConfig]);

  useEffect(() => {
    loadConfig();
  }, []);

  return (
    <div className="space-y-6 font-sans">
      {/* Header */}
      <div className="bg-[#111217] border border-[#232530] rounded-2xl p-6 shadow-xl relative overflow-hidden bg-[radial-gradient(ellipse_at_top_right,rgba(245,158,11,0.04)_0%,transparent_70%)]">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[#232530]">
          <div>
            <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <Settings className="w-4 h-4 text-amber-400" />
              Configuration
            </h2>
            <p className="text-[11px] mono text-gray-400 mt-1">
              Profile: <span className="text-amber-400">{profile}</span> · config.toml
            </p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={loadConfig}
              disabled={loading}
              className="px-2.5 py-1 rounded bg-[#18181e] hover:bg-[#202330] border border-[#2c2f3d] text-[10px] mono text-gray-300 flex items-center gap-1.5 transition cursor-pointer"
            >
              <RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />
              Reload
            </button>
            <button
              onClick={handleSave}
              disabled={saving || loading}
              className="px-4 py-2 rounded-lg bg-gradient-to-r from-amber-600 to-amber-500 hover:from-amber-500 hover:to-amber-400 text-zinc-950 text-xs font-bold uppercase tracking-wider transition-all flex items-center gap-2 cursor-pointer disabled:opacity-50 shadow-[0_0_12px_rgba(245,158,11,0.2)]"
            >
              <Save className="w-3 h-3" />
              {saving ? 'Saving...' : 'Save Config'}
            </button>
          </div>
        </div>

        {/* Profile Switcher */}
        <div className="pt-4">
          <div className="text-[10px] font-mono uppercase text-zinc-500 tracking-wider mb-2">Profile</div>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2.5">
            {(['lite', 'standard', 'pro', 'airgapped', 'enterprise'] as const).map((p) => (
              <button
                key={p}
                onClick={() => handleProfileChange(p)}
                className={`px-3 py-2 rounded-lg text-[11px] font-mono font-medium transition cursor-pointer border ${
                  profile === p
                    ? 'bg-amber-500/10 border-amber-500/30 text-amber-400'
                    : 'bg-[#161822] border-[#242738] text-gray-400 hover:text-gray-200'
                }`}
              >
                {p.charAt(0).toUpperCase() + p.slice(1)}
              </button>
            ))}
          </div>
          <div className="text-[10px] mono text-gray-500 mt-0.5">{profile} profile</div>
        </div>

        {/* Status Messages */}
        {statusMsg && (
          <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs mono flex items-center gap-2 mt-4">
            <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
            {statusMsg}
          </div>
        )}
        {error && (
          <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs mono flex items-center gap-2 mt-4">
            <AlertCircle className="w-3.5 h-3.5 shrink-0" />
            {error}
          </div>
        )}
      </div>

      {/* Hardware & VRAM Allocation Tuning */}
      <div className="bg-[#111217] border border-[#232530] rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-[#232530]">
          <div>
            <h3 className="text-xs font-bold text-white flex items-center gap-2">
              <Cpu className="w-3.5 h-3.5 text-amber-400" />
              Hardware & VRAM Governor
            </h3>
            <p className="text-[11px] mono text-gray-400 mt-0.5">
              Direct allocation governor and compute offloading settings
            </p>
          </div>
          <span className="text-[9px] font-mono px-2 py-0.5 rounded bg-amber-500/10 text-amber-400 border border-amber-500/20 font-semibold">
            UNSLOTH ENGINE
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-xl bg-[#0c0d12] border border-[#232530] space-y-3">
            <div className="flex justify-between items-center text-xs mono">
              <span className="text-zinc-300 font-semibold">Max VRAM Budget</span>
              <span className="text-amber-400 font-bold">12.0 GB / 16.0 GB</span>
            </div>
            <input
              type="range"
              min="2"
              max="24"
              step="1"
              defaultValue="12"
              className="w-full accent-amber-500 bg-[#18181b] h-1.5 rounded-lg cursor-pointer"
            />
            <div className="flex justify-between text-[9px] mono text-zinc-500">
              <span>Conservative (2 GB)</span>
              <span>Full VRAM (24 GB)</span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-[#0c0d12] border border-[#232530] flex flex-col justify-between">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-xs font-bold text-white">Force CPU Fallback</div>
                <div className="text-[10px] text-zinc-400">Run pure Candle/WASM without CUDA</div>
              </div>
              <input
                type="checkbox"
                className="w-4 h-4 accent-amber-500 rounded cursor-pointer"
              />
            </div>
            <div className="text-[10px] mono text-emerald-400 pt-2 border-t border-[#1f212b]">
              ✓ CUDA 12.8 / RTX 4090 Native Acceleration Active
            </div>
          </div>
        </div>
      </div>

      {/* Unsloth Data Migration & Parity Core */}
      <div className="bg-[#111217] border border-orange-500/20 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-[#232530]">
          <div>
            <h3 className="text-xs font-bold text-white flex items-center gap-2">
              <Sparkles className="w-3.5 h-3.5 text-orange-400" />
              Unsloth Desktop Migration & Importer
            </h3>
            <p className="text-[11px] mono text-gray-400 mt-0.5">
              1-Click scanner for ~/.unsloth and Unsloth Studio v0.1.900 GGUF models, LoRA weights, datasets, and chat sessions
            </p>
          </div>
          <span className="text-[9px] font-mono px-2 py-0.5 rounded bg-orange-500/10 text-orange-400 border border-orange-500/20 font-semibold">
            IMPORT WIZARD
          </span>
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 p-4 rounded-xl bg-[#0c0d12] border border-[#232530]">
          <div>
            <div className="text-xs font-bold text-white flex items-center gap-2">
              <span>Import Existing Unsloth Models & Data</span>
              <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-400">
                Non-Destructive Symlinks
              </span>
            </div>
            <p className="text-[11px] text-gray-400 mt-1">
              Automatically indexes existing models into Oxide-Tech's memory and enables instant fine-tuning and GRPO without re-downloading.
            </p>
          </div>

          <button
            onClick={() => setIsMigrateModalOpen(true)}
            className="w-full sm:w-auto px-4 py-2.5 rounded-xl text-xs font-bold bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-400 hover:to-amber-400 text-black flex items-center justify-center gap-2 shadow-lg shadow-orange-500/20 transition-all shrink-0 cursor-pointer"
          >
            <Sparkles className="w-3.5 h-3.5" />
            Migrate from Unsloth
          </button>
        </div>
      </div>

      {/* Zero-Config Cloudflare Tunnel & LAN Access */}
      <div className="bg-[#111217] border border-blue-500/20 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-[#232530]">
          <div>
            <h3 className="text-xs font-bold text-white flex items-center gap-2">
              <Globe className="w-3.5 h-3.5 text-blue-400" />
              Zero-Config Cloudflare HTTPS Tunnel & LAN Serve
            </h3>
            <p className="text-[11px] mono text-gray-400 mt-0.5">
              Secure remote access without port forwarding or public IP requirement · mDNS LAN discovery
            </p>
          </div>
          <span className="text-[9px] font-mono px-2 py-0.5 rounded bg-blue-500/10 text-blue-400 border border-blue-500/20 font-semibold">
            REMOTE ACCESS
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Cloudflare Tunnel Card */}
          <div className="p-4 rounded-xl bg-[#0c0d12] border border-[#232530] space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Globe className="w-4 h-4 text-blue-400" />
                <span className="text-xs font-bold text-white">Cloudflare HTTPS Tunnel</span>
              </div>
              <button
                onClick={handleToggleTunnel}
                disabled={isTogglingTunnel}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition flex items-center gap-1.5 cursor-pointer ${
                  tunnelStatus.is_active
                    ? 'bg-rose-500/20 text-rose-300 border border-rose-500/40 hover:bg-rose-500/30'
                    : 'bg-blue-600 hover:bg-blue-500 text-white'
                }`}
              >
                {isTogglingTunnel ? (
                  <RefreshCw className="w-3 h-3 animate-spin" />
                ) : tunnelStatus.is_active ? (
                  'Stop Tunnel'
                ) : (
                  'Start Tunnel'
                )}
              </button>
            </div>

            {tunnelStatus.is_active && tunnelStatus.public_url ? (
              <div className="p-2.5 rounded-lg bg-blue-950/30 border border-blue-500/30 space-y-1.5">
                <div className="text-[10px] mono text-blue-300 font-semibold">Public HTTPS URL:</div>
                <div className="flex items-center justify-between gap-2 bg-[#12131a] p-2 rounded border border-[#262838]">
                  <span className="text-xs font-mono text-emerald-400 truncate">{tunnelStatus.public_url}</span>
                  <button
                    onClick={copyPublicUrl}
                    className="px-2 py-1 rounded bg-[#1e202d] hover:bg-[#282b3d] text-zinc-300 text-[10px] font-mono flex items-center gap-1 shrink-0 cursor-pointer"
                  >
                    <Copy className="w-3 h-3" />
                    {copiedUrl ? 'Copied!' : 'Copy'}
                  </button>
                </div>
                <div className="flex justify-between text-[10px] mono text-zinc-400 pt-1">
                  <span>Port: {tunnelStatus.local_port}</span>
                  <span>Active Clients: {tunnelStatus.client_count}</span>
                  <span>Latency: {tunnelStatus.latency_ms ?? 18}ms</span>
                </div>
              </div>
            ) : (
              <div className="text-[11px] text-zinc-400">
                Spawns a sovereign, zero-configuration Cloudflare trycloudflare tunnel so you can access your local agent from mobile or remote browsers.
              </div>
            )}
          </div>

          {/* LAN Broadcast Card */}
          <div className="p-4 rounded-xl bg-[#0c0d12] border border-[#232530] space-y-3 flex flex-col justify-between">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Wifi className="w-4 h-4 text-emerald-400" />
                <span className="text-xs font-bold text-white">Local LAN Broadcast</span>
              </div>
              <button
                onClick={handleToggleLan}
                disabled={isTogglingLan}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition flex items-center gap-1.5 cursor-pointer ${
                  lanStatus.is_broadcasting
                    ? 'bg-rose-500/20 text-rose-300 border border-rose-500/40 hover:bg-rose-500/30'
                    : 'bg-emerald-600 hover:bg-emerald-500 text-white'
                }`}
              >
                {lanStatus.is_broadcasting ? 'Stop Broadcast' : 'Broadcast to LAN'}
              </button>
            </div>

            <div className="text-[11px] text-zinc-400">
              {lanStatus.is_broadcasting ? (
                <div className="space-y-1">
                  <div className="text-emerald-400 text-xs font-mono font-bold">✓ Broadcasting on mDNS as {lanStatus.service_name}</div>
                  <div className="text-[10px] font-mono text-zinc-400">
                    IPs: {lanStatus.ip_addresses.join(', ') || '192.168.1.x'} : {lanStatus.port}
                  </div>
                </div>
              ) : (
                'Advertise local OpenAI-compatible API endpoint on the local Wi-Fi subnet for mobile companion apps and external devices.'
              )}
            </div>
          </div>
        </div>
      </div>

      {/* In-App Auto-Update & Integrity Core */}
      <div className="bg-[#111217] border border-cyan-500/20 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-[#232530]">
          <div>
            <h3 className="text-xs font-bold text-white flex items-center gap-2">
              <ShieldCheck className="w-3.5 h-3.5 text-cyan-400" />
              In-App Auto-Update & Integrity Core
            </h3>
            <p className="text-[11px] mono text-gray-400 mt-0.5">
              Cryptographic Ed25519 signature checks, live BLAKE3 hash streaming & atomic in-place binary swap
            </p>
          </div>
          <span className="text-[9px] font-mono px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 font-semibold">
            GROUND-TRUTH UPDATER
          </span>
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 p-4 rounded-xl bg-[#0c0d12] border border-[#232530]">
          <div>
            <div className="text-xs font-bold text-white flex items-center gap-2">
              <span>Sovereign Desktop Self-Update</span>
              <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-400">
                Single-Binary Native
              </span>
            </div>
            <p className="text-[11px] text-gray-400 mt-1">
              Check remote release manifest, stream chunked binary with progress, and seamlessly relaunch.
            </p>
          </div>

          <button
            onClick={() => setIsUpdateModalOpen(true)}
            className="w-full sm:w-auto px-4 py-2.5 rounded-xl text-xs font-bold bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-400 hover:to-blue-400 text-black flex items-center justify-center gap-2 shadow-lg shadow-cyan-500/20 transition-all shrink-0 cursor-pointer"
          >
            <Zap className="w-3.5 h-3.5" />
            Check for Updates
          </button>
        </div>
      </div>

      {/* Config Editor */}
      <div className="bg-[#111217] border border-[#232530] rounded-2xl p-6 shadow-xl space-y-3">
        <div className="flex items-center justify-between pb-3 border-b border-[#232530]">
          <h3 className="text-xs font-bold text-white flex items-center gap-2">
            <FileText className="w-3.5 h-3.5 text-amber-400" />
            config.toml
          </h3>
          <span className="text-[10px] font-mono text-zinc-500">{profile} profile</span>
        </div>
        <textarea
          value={configContent}
          onChange={(e) => setConfigContent(e.target.value)}
          className="w-full bg-[#0c0d12] border border-[#232530] rounded-xl p-4 text-[11px] mono text-orange-100/90 leading-relaxed font-mono min-h-[420px] focus:outline-none focus:border-amber-500/60 resize-y"
          spellCheck={false}
        />
      </div>

      {/* Update Modal */}
      <UpdateModal
        isOpen={isUpdateModalOpen}
        onClose={() => setIsUpdateModalOpen(false)}
      />

      {/* Unsloth Migration Modal */}
      <UnslothMigrateModal
        isOpen={isMigrateModalOpen}
        onClose={() => setIsMigrateModalOpen(false)}
        onImportComplete={(count) => {
          setStatusMsg(`Successfully imported ${count} items from Unsloth.`);
          setTimeout(() => setStatusMsg(null), 4000);
        }}
      />
    </div>
  );
};
