# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ridge.proto\x12\x0coxide.bridge\"=\n\x0eNetlistRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x17\n\x0f\x66latbuffer_data\x18\x02 \x01(\x0c\"D\n\x0fNetlistResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06report\x18\x02 \x01(\t\x12\x10\n\x08warnings\x18\x03 \x03(\t\"I\n\x0eThermalRequest\x12\x16\n\x0epcb_model_path\x18\x01 \x01(\t\x12\x1f\n\x17power_dissipation_watts\x18\x02 \x01(\x02\"A\n\x0fThermalResponse\x12\x13\n\x0bheat_matrix\x18\x01 \x03(\x02\x12\x19\n\x11peak_temp_celsius\x18\x02 \x01(\x02\x32\xb3\x01\n\rBridgeService\x12M\n\x0e\x41nalyzeNetlist\x12\x1c.oxide.bridge.NetlistRequest\x1a\x1d.oxide.bridge.NetlistResponse\x12S\n\x14RunThermalSimulation\x12\x1c.oxide.bridge.ThermalRequest\x1a\x1d.oxide.bridge.ThermalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NETLISTREQUEST']._serialized_start=30
  _globals['_NETLISTREQUEST']._serialized_end=91
  _globals['_NETLISTRESPONSE']._serialized_start=93
  _globals['_NETLISTRESPONSE']._serialized_end=161
  _globals['_THERMALREQUEST']._serialized_start=163
  _globals['_THERMALREQUEST']._serialized_end=236
  _globals['_THERMALRESPONSE']._serialized_start=238
  _globals['_THERMALRESPONSE']._serialized_end=303
  _globals['_BRIDGESERVICE']._serialized_start=306
  _globals['_BRIDGESERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
