# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bridge_pb2 as bridge__pb2


class BridgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeNetlist = channel.unary_unary(
                '/oxide.bridge.BridgeService/AnalyzeNetlist',
                request_serializer=bridge__pb2.NetlistRequest.SerializeToString,
                response_deserializer=bridge__pb2.NetlistResponse.FromString,
                )
        self.RunThermalSimulation = channel.unary_unary(
                '/oxide.bridge.BridgeService/RunThermalSimulation',
                request_serializer=bridge__pb2.ThermalRequest.SerializeToString,
                response_deserializer=bridge__pb2.ThermalResponse.FromString,
                )


class BridgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeNetlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunThermalSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeNetlist': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeNetlist,
                    request_deserializer=bridge__pb2.NetlistRequest.FromString,
                    response_serializer=bridge__pb2.NetlistResponse.SerializeToString,
            ),
            'RunThermalSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunThermalSimulation,
                    request_deserializer=bridge__pb2.ThermalRequest.FromString,
                    response_serializer=bridge__pb2.ThermalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oxide.bridge.BridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BridgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeNetlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/oxide.bridge.BridgeService/AnalyzeNetlist',
            bridge__pb2.NetlistRequest.SerializeToString,
            bridge__pb2.NetlistResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunThermalSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/oxide.bridge.BridgeService/RunThermalSimulation',
            bridge__pb2.ThermalRequest.SerializeToString,
            bridge__pb2.ThermalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
