use serde::{Deserialize, Serialize};

/// High-level web automation action recorded from user interaction or generated by ReAct agent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "action", rename_all = "snake_case")]
pub enum WebAction {
    Navigate {
        url: String,
    },
    Click {
        selector: String,
    },
    Type {
        selector: String,
        text: String,
    },
    Hover {
        selector: String,
    },
    WaitForSelector {
        selector: String,
        #[serde(default = "default_timeout_ms")]
        timeout_ms: u64,
    },
    PressKey {
        key: String,
    },
    AssertText {
        selector: String,
        expected: String,
    },
}

fn default_timeout_ms() -> u64 {
    5000
}

/// A serialized sequence of web actions forming an end-to-end user journey or test script.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WebScript {
    pub name: String,
    pub description: Option<String>,
    pub actions: Vec<WebAction>,
}

impl WebScript {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: None,
            actions: Vec::new(),
        }
    }

    pub fn add_action(&mut self, action: WebAction) -> &mut Self {
        self.actions.push(action);
        self
    }
}

/// Synthesizes recorded interaction scripts into compiled Rust macros for `self-evolver` crystallization.
#[derive(Debug, Default)]
pub struct MacroCodegen;

impl MacroCodegen {
    /// Generates idiomatic Rust asynchronous test/execution code for a given `WebScript`.
    pub fn generate_rust_code(script: &WebScript) -> String {
        let mut code = String::new();
        code.push_str(&format!(
            "// Generated by web-forge Codegen for: {}\n",
            script.name
        ));
        code.push_str("pub async fn execute_flow<H: WebHarness>(harness: &mut H) -> Result<(), WebForgeError> {\n");

        for action in &script.actions {
            match action {
                WebAction::Navigate { url } => {
                    code.push_str(&format!("    harness.navigate(\"{}\").await?;\n", url));
                }
                WebAction::Click { selector } => {
                    code.push_str(&format!("    harness.click(\"{}\").await?;\n", selector));
                }
                WebAction::Type { selector, text } => {
                    code.push_str(&format!(
                        "    harness.type_text(\"{}\", \"{}\").await?;\n",
                        selector, text
                    ));
                }
                WebAction::Hover { selector } => {
                    code.push_str(&format!("    harness.hover(\"{}\").await?;\n", selector));
                }
                WebAction::WaitForSelector {
                    selector,
                    timeout_ms,
                } => {
                    code.push_str(&format!(
                        "    harness.wait_for_selector(\"{}\", std::time::Duration::from_millis({})).await?;\n",
                        selector, timeout_ms
                    ));
                }
                WebAction::PressKey { key } => {
                    code.push_str(&format!("    harness.press_key(\"{}\").await?;\n", key));
                }
                WebAction::AssertText { selector, expected } => {
                    code.push_str(&format!(
                        "    harness.assert_text(\"{}\", \"{}\").await?;\n",
                        selector, expected
                    ));
                }
            }
        }

        code.push_str("    Ok(())\n}\n");
        code
    }

    /// Generates a reusable Rust declarative macro (`nexus_macro::...`) for instant replay.
    pub fn generate_macro(script: &WebScript) -> String {
        let macro_name = script.name.to_lowercase().replace(['-', ' '], "_");
        let mut code = String::new();

        code.push_str(&format!("/// Crystallized macro for {}\n", script.name));
        code.push_str("#[macro_export]\n");
        code.push_str(&format!("macro_rules! {} {{\n", macro_name));
        code.push_str("    ($harness:expr) => {{\n");
        code.push_str("        async {\n");

        for action in &script.actions {
            match action {
                WebAction::Navigate { url } => {
                    code.push_str(&format!(
                        "            $harness.navigate(\"{}\").await?;\n",
                        url
                    ));
                }
                WebAction::Click { selector } => {
                    code.push_str(&format!(
                        "            $harness.click(\"{}\").await?;\n",
                        selector
                    ));
                }
                WebAction::Type { selector, text } => {
                    code.push_str(&format!(
                        "            $harness.type_text(\"{}\", \"{}\").await?;\n",
                        selector, text
                    ));
                }
                WebAction::Hover { selector } => {
                    code.push_str(&format!(
                        "            $harness.hover(\"{}\").await?;\n",
                        selector
                    ));
                }
                WebAction::WaitForSelector {
                    selector,
                    timeout_ms,
                } => {
                    code.push_str(&format!(
                        "            $harness.wait_for_selector(\"{}\", std::time::Duration::from_millis({})).await?;\n",
                        selector, timeout_ms
                    ));
                }
                WebAction::PressKey { key } => {
                    code.push_str(&format!(
                        "            $harness.press_key(\"{}\").await?;\n",
                        key
                    ));
                }
                WebAction::AssertText { selector, expected } => {
                    code.push_str(&format!(
                        "            $harness.assert_text(\"{}\", \"{}\").await?;\n",
                        selector, expected
                    ));
                }
            }
        }

        code.push_str("            Ok::<(), WebForgeError>(())\n");
        code.push_str("        }\n");
        code.push_str("    }};\n");
        code.push_str("}\n");

        code
    }
}
