use std::collections::HashMap;
use uuid::Uuid;

use crate::constraint_solver::ConstraintSolver;
use crate::dag::{CadOperation, FeatureDAG, Plane};
use crate::ParametricError;

/// Evaluated 3D solid geometry generated by topological traversal of the Feature DAG.
#[derive(Debug, Clone, PartialEq)]
pub struct EvaluatedSolid {
    pub op_id: Uuid,
    pub name: String,
    pub vertices: Vec<[f64; 3]>,
    pub faces: Vec<Vec<usize>>,
    pub bounding_box: ([f64; 3], [f64; 3]),
    pub volume: f64,
}

/// Evaluates the Parametric Feature DAG from root sketches to final 3D features.
#[derive(Debug, Default)]
pub struct DagEvaluator;

impl DagEvaluator {
    pub fn new() -> Self {
        Self
    }

    /// Evaluates all features in the DAG in topological order, solving sketches and generating solids.
    pub fn evaluate(&self, dag: &mut FeatureDAG) -> Result<Vec<EvaluatedSolid>, ParametricError> {
        let order = dag.topological_order()?;
        let mut evaluated_solids: Vec<EvaluatedSolid> = Vec::new();
        let mut sketch_profiles: HashMap<Uuid, Vec<[f64; 3]>> = HashMap::new();

        for node_idx in order {
            // First solve sketch if operation is Sketch2D
            let op = &mut dag.graph[node_idx];
            match op {
                CadOperation::Sketch2D {
                    id,
                    name: _,
                    plane,
                    points,
                    constraints,
                    ..
                } => {
                    // 1. Solve 2D sketch constraints deterministically
                    ConstraintSolver::solve_sketch(constraints, points, 100, 1e-6)?;

                    // 2. Project 2D points to 3D plane
                    let pts_3d = Self::project_to_3d(points, *plane);
                    sketch_profiles.insert(*id, pts_3d);
                }
                CadOperation::Extrude {
                    id,
                    name,
                    profile_id,
                    distance,
                    direction,
                } => {
                    let profile_pts = sketch_profiles.get(profile_id).ok_or_else(|| {
                        ParametricError::InvalidParameter(format!(
                            "Extrude '{}' references unknown or un-evaluated sketch profile '{}'",
                            name, profile_id
                        ))
                    })?;

                    if profile_pts.len() < 3 {
                        return Err(ParametricError::DegenerateGeometry(format!(
                            "Sketch profile '{}' must contain at least 3 points to form a closed face",
                            profile_id
                        )));
                    }

                    let solid = Self::extrude_profile(*id, name, profile_pts, *distance, *direction)?;
                    evaluated_solids.push(solid);
                }
                CadOperation::Fillet {
                    id: _,
                    name,
                    target_op_id,
                    target_edges: _,
                    radius,
                } => {
                    // Check if target solid exists and validate fillet radius against bounding box
                    if let Some(target_solid) = evaluated_solids.iter().find(|s| s.op_id == *target_op_id) {
                        let (min_b, max_b) = target_solid.bounding_box;
                        let min_dim = (max_b[0] - min_b[0])
                            .min(max_b[1] - min_b[1])
                            .min(max_b[2] - min_b[2]);

                        if *radius > min_dim * 0.5 {
                            return Err(ParametricError::GeometricInvariantViolation(format!(
                                "Fillet '{}' radius {:.2}mm exceeds maximum feasible thickness ({:.2}mm)",
                                name,
                                radius,
                                min_dim * 0.5
                            )));
                        }
                    }
                }
                CadOperation::Chamfer {
                    id: _,
                    name,
                    target_op_id,
                    target_edges: _,
                    distance,
                } => {
                    if let Some(target_solid) = evaluated_solids.iter().find(|s| s.op_id == *target_op_id) {
                        let (min_b, max_b) = target_solid.bounding_box;
                        let min_dim = (max_b[0] - min_b[0])
                            .min(max_b[1] - min_b[1])
                            .min(max_b[2] - min_b[2]);

                        if *distance > min_dim * 0.5 {
                            return Err(ParametricError::GeometricInvariantViolation(format!(
                                "Chamfer '{}' distance {:.2}mm exceeds maximum feasible thickness ({:.2}mm)",
                                name,
                                distance,
                                min_dim * 0.5
                            )));
                        }
                    }
                }
                CadOperation::Boolean { .. } => {
                    // CSG Boolean combination
                }
            }
        }

        Ok(evaluated_solids)
    }

    /// Project 2D sketch points onto the specified 3D plane.
    fn project_to_3d(points: &[[f64; 2]], plane: Plane) -> Vec<[f64; 3]> {
        points
            .iter()
            .map(|&[x, y]| match plane {
                Plane::XY => [x, y, 0.0],
                Plane::XZ => [x, 0.0, y],
                Plane::YZ => [0.0, x, y],
                Plane::Custom { origin, normal: _ } => [origin[0] + x, origin[1] + y, origin[2]],
            })
            .collect()
    }

    /// Extrude a 3D closed polygon profile along a direction vector by distance.
    fn extrude_profile(
        id: Uuid,
        name: &str,
        profile: &[[f64; 3]],
        distance: f64,
        direction: [f64; 3],
    ) -> Result<EvaluatedSolid, ParametricError> {
        let n = profile.len();
        let dir_norm = (direction[0] * direction[0]
            + direction[1] * direction[1]
            + direction[2] * direction[2])
            .sqrt();
        let dir_unit = if dir_norm > 1e-6 {
            [
                direction[0] / dir_norm,
                direction[1] / dir_norm,
                direction[2] / dir_norm,
            ]
        } else {
            [0.0, 0.0, 1.0]
        };

        let offset = [
            dir_unit[0] * distance,
            dir_unit[1] * distance,
            dir_unit[2] * distance,
        ];

        let mut vertices = Vec::with_capacity(2 * n);
        // Base profile (indices 0..n)
        for &p in profile {
            vertices.push(p);
        }
        // Extruded profile (indices n..2n)
        for &p in profile {
            vertices.push([p[0] + offset[0], p[1] + offset[1], p[2] + offset[2]]);
        }

        let mut faces = Vec::new();
        // Bottom face
        faces.push((0..n).collect());
        // Top face
        faces.push((n..2 * n).rev().collect());
        // Side quad faces
        for i in 0..n {
            let next_i = (i + 1) % n;
            faces.push(vec![i, next_i, next_i + n, i + n]);
        }

        // Calculate bounding box
        let mut min_b = [f64::INFINITY, f64::INFINITY, f64::INFINITY];
        let mut max_b = [f64::NEG_INFINITY, f64::NEG_INFINITY, f64::NEG_INFINITY];
        for v in &vertices {
            for k in 0..3 {
                if v[k] < min_b[k] {
                    min_b[k] = v[k];
                }
                if v[k] > max_b[k] {
                    max_b[k] = v[k];
                }
            }
        }

        // Approximate volume from bounding box / polygon area * distance
        let width = (max_b[0] - min_b[0]).max(0.0);
        let height = (max_b[1] - min_b[1]).max(0.0);
        let depth = (max_b[2] - min_b[2]).max(0.0);
        let volume = width * height * depth;

        Ok(EvaluatedSolid {
            op_id: id,
            name: name.to_string(),
            vertices,
            faces,
            bounding_box: (min_b, max_b),
            volume,
        })
    }
}
