[package]
name = "oxide-protocol"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
flatbuffers = "25.12.19"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
blake3 = { workspace = true }
async-trait = "0.1"

[build-dependencies]
blake3 = { workspace = true }
