[package]
name = "router"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
memory = { path = "../memory" }
serde = { workspace = true }
serde_json = { workspace = true }
ndarray = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
reqwest = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
surrealdb-service = { path = "../../crates/surrealdb-service" }

[dev-dependencies]
verifier = { path = "../verifier" }


