[package]
name = "surrealdb-service"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = { workspace = true }
tree-sitter-service = { path = "../tree-sitter-service" }
serde = { workspace = true }
serde_json = { workspace = true }
surrealdb-types = { workspace = true }
chrono = { workspace = true }
common = { path = "../../workspace/common" }
