[package]
name = "mcp-live-docs"
version = "0.1.0"
edition = "2021"

[dependencies]
rmcp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
reqwest = { workspace = true }
select = "0.6.1"
regex = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
schemars = { version = "1.2.1", features = ["derive"] }
config-loader = { path = "../config-loader" }
sandbox = { path = "../sandbox" }
anyhow = { workspace = true }

