use petgraph::visit::EdgeRef;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

use crate::netlist::{CircuitGraph, NetlistNode};

/// Structured topology issue for automated ReAct feedback in `optio`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TopologyIssue {
    pub rule_id: String,
    pub severity: String,
    pub target_ref: Option<String>,
    pub message: String,
}

/// Comprehensive Electrical Rule Check (ERC) report generated by graph traversal.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErcReport {
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
    pub issues: Vec<TopologyIssue>,
}

impl ErcReport {
    /// Returns true if there are no ERC errors.
    pub fn is_clean(&self) -> bool {
        self.errors.is_empty()
    }

    /// Returns true if there are any ERC warnings.
    pub fn has_warnings(&self) -> bool {
        !self.warnings.is_empty()
    }

    /// Add an error to the report.
    pub fn add_error(
        &mut self,
        rule_id: &str,
        target_ref: Option<&str>,
        message: impl Into<String>,
    ) {
        let msg = message.into();
        self.errors.push(msg.clone());
        self.issues.push(TopologyIssue {
            rule_id: rule_id.to_string(),
            severity: "ERROR".to_string(),
            target_ref: target_ref.map(|s| s.to_string()),
            message: msg,
        });
    }

    /// Add a warning to the report.
    pub fn add_warning(
        &mut self,
        rule_id: &str,
        target_ref: Option<&str>,
        message: impl Into<String>,
    ) {
        let msg = message.into();
        self.warnings.push(msg.clone());
        self.issues.push(TopologyIssue {
            rule_id: rule_id.to_string(),
            severity: "WARNING".to_string(),
            target_ref: target_ref.map(|s| s.to_string()),
            message: msg,
        });
    }
}

/// Run deterministic Electrical Rule Checking (ERC) on a circuit bipartite graph.
pub fn run_erc(graph: &CircuitGraph) -> ErcReport {
    let mut report = ErcReport::default();
    let mut ref_des_counts: HashMap<String, usize> = HashMap::new();
    let mut power_nets: HashSet<String> = HashSet::new();
    let mut gnd_nets: HashSet<String> = HashSet::new();

    // Identify power rails and ground nets
    for node_idx in graph.node_indices() {
        if let NetlistNode::Net { name, .. } = &graph[node_idx] {
            let upper = name.to_uppercase();
            if upper == "VCC"
                || upper == "VDD"
                || upper == "+3.3V"
                || upper == "+5V"
                || upper == "+12V"
                || upper == "3V3"
                || upper == "5V"
                || upper == "VIN"
                || upper == "VBAT"
            {
                power_nets.insert(name.clone());
            } else if upper == "GND" || upper == "0V" || upper == "AGND" || upper == "DGND" {
                gnd_nets.insert(name.clone());
            }
        }
    }

    // Traversal: Check Net nodes & Component nodes
    for node_idx in graph.node_indices() {
        match &graph[node_idx] {
            NetlistNode::Net { name, .. } => {
                let edges: Vec<_> = graph.edges(node_idx).collect();
                let degree = edges.len();

                // Rule 1: Floating Nets (degree < 2)
                if degree == 0 {
                    report.add_error(
                        "ERC_FLOATING_NET",
                        Some(name),
                        format!(
                            "ERC Error: Net '{}' is completely unconnected (0 pins attached).",
                            name
                        ),
                    );
                } else if degree == 1 {
                    let edge = edges[0];
                    let comp_node = edge.target();
                    let pin_name = &edge.weight().pin_name;
                    let comp_ref = graph[comp_node].ref_des().unwrap_or("Unknown");
                    report.add_error(
                        "ERC_FLOATING_NET",
                        Some(name),
                        format!(
                            "ERC Error: Net '{}' is floating (connected to only 1 pin: {}.{}).",
                            name, comp_ref, pin_name
                        ),
                    );
                }
            }
            NetlistNode::Component {
                ref_des,
                lib_id,
                value: _,
                footprint: _,
            } => {
                *ref_des_counts.entry(ref_des.clone()).or_insert(0) += 1;

                let degree = graph.edges(node_idx).count();
                // Rule 2: Unconnected / Isolated Components
                if degree == 0 {
                    report.add_error(
                        "ERC_ISOLATED_COMPONENT",
                        Some(ref_des),
                        format!(
                            "ERC Error: Component '{}' ({}) has no pin connections.",
                            ref_des, lib_id
                        ),
                    );
                }
            }
        }
    }

    // Rule 3: Duplicate Reference Designators
    for (ref_des, count) in ref_des_counts {
        if count > 1 {
            report.add_error(
                "ERC_DUPLICATE_REF_DES",
                Some(&ref_des),
                format!(
                    "ERC Error: Duplicate reference designator '{}' used {} times.",
                    ref_des, count
                ),
            );
        }
    }

    // Rule 4: Power Rail Decoupling Check
    // For every power rail (VCC/VDD), verify that a capacitor bridges it to GND
    if !gnd_nets.is_empty() {
        for power_net in &power_nets {
            let mut has_decoupling_cap = false;

            // Find all components connected to this power net
            for node_idx in graph.node_indices() {
                if let NetlistNode::Net { name, .. } = &graph[node_idx] {
                    if name != power_net {
                        continue;
                    }
                    for edge in graph.edges(node_idx) {
                        let comp_node = edge.target();
                        if let NetlistNode::Component {
                            ref_des, lib_id, ..
                        } = &graph[comp_node]
                        {
                            let is_cap = ref_des.starts_with('C')
                                || lib_id.contains(":C")
                                || lib_id.contains("Capacitor");

                            if is_cap {
                                // Check if this capacitor also connects to a GND net
                                for comp_edge in graph.edges(comp_node) {
                                    let target_net_node = comp_edge.target();
                                    let is_gnd_target = graph[target_net_node]
                                        .net_name()
                                        .map(|net_name| gnd_nets.contains(net_name))
                                        .unwrap_or(false);

                                    if is_gnd_target {
                                        has_decoupling_cap = true;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            if !has_decoupling_cap {
                report.add_warning(
                    "ERC_MISSING_DECOUPLING",
                    Some(power_net),
                    format!(
                        "ERC Warning: Power rail '{}' lacks a decoupling capacitor bridging to GND.",
                        power_net
                    ),
                );
            }
        }
    }

    report
}
