use serde::{Deserialize, Serialize};
use std::collections::{HashSet, VecDeque};
use crate::code_graph::{CodeEdgeType, MultiModalCodeGraph};

/// Report generated by the Impact Analysis & Change Propagation Engine
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ImpactAnalysisReport {
    pub target_symbol: String,
    pub blast_radius_count: usize,
    pub impacted_nodes: Vec<String>,
    pub impacted_files: Vec<String>,
    pub recommended_tests: Vec<String>,
    pub risk_level: ImpactRiskLevel,
}

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
pub enum ImpactRiskLevel {
    Low,
    Medium,
    High,
    Critical,
}

pub struct ImpactAnalysisEngine;

impl ImpactAnalysisEngine {
    /// Calculate downstream blast radius for a given modified node
    pub fn analyze(graph: &MultiModalCodeGraph, target_id: &str) -> ImpactAnalysisReport {
        let mut impacted_nodes_set = HashSet::new();
        let mut impacted_files_set = HashSet::new();
        let mut queue = VecDeque::new();

        queue.push_back(target_id.to_string());

        while let Some(current_id) = queue.pop_front() {
            // Check incoming callers/dependents (who depends on current_id?)
            if let Some(incoming) = graph.incoming_edges.get(&current_id) {
                for edge in incoming {
                    // Traversing dependencies that propagate changes
                    match edge.edge_type {
                        CodeEdgeType::Calls
                        | CodeEdgeType::Implements
                        | CodeEdgeType::References
                        | CodeEdgeType::Mutates
                        | CodeEdgeType::PassesTo => {
                            if impacted_nodes_set.insert(edge.from_id.clone()) {
                                if let Some(node) = graph.nodes.get(&edge.from_id) {
                                    impacted_files_set.insert(node.file_path.clone());
                                }
                                queue.push_back(edge.from_id.clone());
                            }
                        }
                        _ => {}
                    }
                }
            }
        }

        let blast_radius_count = impacted_nodes_set.len();

        let risk_level = match blast_radius_count {
            0..=2 => ImpactRiskLevel::Low,
            3..=7 => ImpactRiskLevel::Medium,
            8..=20 => ImpactRiskLevel::High,
            _ => ImpactRiskLevel::Critical,
        };

        // Determine recommended tests based on impacted files and naming conventions
        let mut recommended_tests = Vec::new();
        for file in &impacted_files_set {
            if file.contains("test") {
                recommended_tests.push(file.clone());
            } else {
                let test_name = format!("test_{}", std::path::Path::new(file).file_stem().and_then(|s| s.to_str()).unwrap_or("unit"));
                recommended_tests.push(test_name);
            }
        }

        ImpactAnalysisReport {
            target_symbol: target_id.to_string(),
            blast_radius_count,
            impacted_nodes: impacted_nodes_set.into_iter().collect(),
            impacted_files: impacted_files_set.into_iter().collect(),
            recommended_tests,
            risk_level,
        }
    }
}
